### ISSUE TITLE
Unable to see selection in UI text fields

### ISSUE THREAD

**Issue by cdaddr** [catppuccin/jetbrains#111]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

In certain UI text fields, the selection colour matches the field's background colour, so the selection is not visible.  An example is the search field in Settings.

I think the problem is in `generateFlavours/ui.theme.json`, `TextField` has `"background": "secondaryBackground"`, but `secondaryBackground` is the same colour as `selectionBackground`.   For example in Frappe, they're both `#414559`.

A possible fix is to set `TextField` selection background to something else.  In my screenshot I set it to `panelBackground`. Or maybe another colour would be better?

### Attach screenshots.

Current
<img width="789" alt="Screenshot 2023-11-10 at 1 25 04 PM" src="https://github.com/catppuccin/jetbrains/assets/33412/ed211eb0-8383-444c-a4ea-0318e15efaaf">

with `"selectionBackground": "panelBackground"`
<img width="757" alt="Screenshot 2023-11-10 at 1 27 15 PM" src="https://github.com/catppuccin/jetbrains/assets/33412/1d6e8d54-a7e0-4187-ad46-29e179b421e9">

### What IDE(s) are you seeing the problem on?

GoLand 2023.2.4, WebStorm 2023.2.4

**Comment by turbits** [comment]
Can confirm, noticed this in rename window; "Common" is selected here..
![image](https://github.com/catppuccin/jetbrains/assets/19148607/cbc25418-c446-4fa4-bf84-37248d0ccff3)

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for raising this! I have little time and motivation to focus on bug-fixing this repository at the moment, I can try to carve out some time next week for this :+1: 

As for what colour the highlight should be, I'd like for it to match the [`SELECTION_BACKGROUND`](https://github.com/catppuccin/jetbrains/blob/8aa673bbfa9a4688924dba8a2b6e037d3417ca06/generateFlavours/editor.xml#L60) from the editor so that they are the same but this may be not great when actually applied.

I believe the `secondaryBackground` should only be used for elements that are not editable/selectable so I might actually rename that to lower the chances of this happening in the future.

**Comment by sgoudham** [comment]
@DavidVollmers The only workaround that I can think of at the minute is listed below:

1. Enable [LaF Defaults](https://plugins.jetbrains.com/docs/intellij/internal-ui-laf-defaults.html) window

2. Open the LaF Window (I usually press `Shift+Shift` and search for `LaF Defaults`)

3. Search for `TextField.selectionBackground` and change the hex colour accordingly.

	Here is an example of me changing it to `#414356` when using Mocha
	![image](https://github.com/catppuccin/jetbrains/assets/58985301/67f5e74e-6bcd-4c6d-8934-bdb7ff41e922)

IIRC, the LaF defaults are reset upon restart so you would have to execute the above steps **every time you boot up an instance of the IDE**.
