### ISSUE TITLE
Variance from Neovim version

### ISSUE THREAD

**Issue by jasonsturges** [catppuccin/jetbrains#125]
Really love the appearance of the [Neovim version](https://github.com/catppuccin/nvim), but the JetBrains version feels off:

https://github.com/catppuccin/jetbrains/assets/1213591/b41e8a08-a5b1-402f-9870-bd0861f54e11

Is this intentional?

Maybe I'm not understanding application of the design aesthetic here.

**Comment by sgoudham** [comment]
Hey :wave: 

The neovim version did come first but over the past year, @nekowinston and I took the core highlights from neovim and iterated on them to create the current [editor style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#code-editors).

If you compare JetBrains and VSCode, you'll find that the highlights are a lot more similar, (of course, they can't be 1:1 since they use different parsers and have different restrictions on theming the UI) but we still have some work to do in the organisation to go back and update our older editors to conform to the new highlighting.

E.g. VSCode / JetBrains

![image](https://github.com/catppuccin/jetbrains/assets/58985301/352f4077-e728-4486-82f1-54942ae7c618)

I appreciate that many people really like Neovim's syntax highlighting but we found that it lacked _coherence_ and _consistency_ across multiple languages and hence defined a newer style guide. Note that this is still a work in progress and we need to document more of the similarities that you'll find between JetBrains/VSCode.

Although, I believe that the `gradle.properties` in JetBrains should actually have `blue` keys there :eyes: 

All that to say, yes it is intentional and we actually need to update Neovim to be more in line with JetBrains, VSCode, etc.

**Comment by sgoudham** [comment]
In terms of the design aesthetic, you can view this [storybook instance](https://64f6559f5a0a0c65d3bf4e7a-hucgsbrhjp.chromatic.com/?path=%2Fstory%2Fsyntax--bash) to understand the _vibe_ that we're going for regarding syntax highlighting.

**Comment by jasonsturges** [comment]
@sgoudham Really appreciate these insights - thanks.
