### ISSUE TITLE
It is difficult to distinguish the color of variables and text in Vue

### ISSUE THREAD

**Issue by Nice-CareFree** [catppuccin/jetbrains#177]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

![image](https://github.com/user-attachments/assets/9c715148-537c-4e52-8584-3efe7d94a7ed)
It is difficult to distinguish the color of variables and text in Vue

### What IDE(s) are you seeing the problem on?

IntelliJ IDEA 2023.2.3 (Ultimate Edition)

**Comment by sgoudham** [comment]
Hey 👋,

I'm not a Vue developer but am I right in saying that you want the text `{{ totalCount }}` to be highlighted a different colour? I'd appreciate if you could tell me what you expect with the red arrows that you've added to the screenshot as it's not immediately obvious to me.

Thanks!

**Comment by Nice-CareFree** [comment]
> Hey 👋, 嘿👋，
> 
> I'm not a Vue developer but am I right in saying that you want the text `{{ totalCount }}` to be highlighted a different colour? I'd appreciate if you could tell me what you expect with the red arrows that you've added to the screenshot as it's not immediately obvious to me.我不是 Vue 开发人员，但我说你希望文本`{{ totalCount }}`以不同的颜色突出显示，对吗？如果您能告诉我您对屏幕截图中添加的红色箭头的期望，我将不胜感激，因为它对我来说并不是很明显。
> 
> Thanks! 谢谢！

What I mean is that variables should have another prominent color. The arrow pointing to {{}} inside is the variable name, followed by plain text, but their colors are actually the same and cannot be distinguished

**Comment by sgoudham** [comment]
Hey again,

I looked into this earlier today. It looks like JetBrains doesn't have a customisable syntax highlighter for Vue templates but rather inherits from other syntaxes like Javascript and HTML. 

The variable is inherited from `Javascript.Object.Property` and because it's inherited, changing the variable colour for the Vue template means changing the colour of object properties in Javascript. We don't highlight properties any differently as per our style guide so I will be closing this issue as not planned.

However, if you would like to override the colour for yourself, you can head to `Settings` -> `Color Scheme` -> `Javascript` and modify the value for `Object.Property`. See the screenshot below where I've changed the colour to a shade of blue:

![image](https://github.com/user-attachments/assets/5e4358fd-2bbc-4b80-ba6e-066cc5d614e3)

Hope that's okay!
