### ISSUE TITLE
Some file colors are illegible in Latte

### ISSUE THREAD

**Issue by vctls** [catppuccin/jetbrains#20]
Just installed v2 via the released file on PhpStorm 2022.2.3.
Although they work well in Mocha and Macchiato, some file colors don't seem to have their corresponding match in Latte.
![image](https://user-images.githubusercontent.com/18054077/197386530-fcd5eaef-924f-4950-b2c7-a36f5e07a1df.png)

I could use custom colors, but then those wouldn't change when switching from light to dark theme.

**Comment by sgoudham** [comment]
Ah, thanks for bringing this to our attention! 

It looks like the violating code is around [here](https://github.com/catppuccin/jetbrains/blob/caacf303b6421d7df9bb7f1275ce0f9742bb9367/generateScheme/main.ts#L188) where I'm bringing down the opacity but forgot to consider Latte which wouldn't look the best!

This should be a somewhat easy fix. I'll try to get around to this by the end of the day and bump up the release to a minor version. Unfortunately uploading it to the marketplace seems to have a manual review process so that would take longer.

If you are still wanting to use Latte, I'd recommend disabling the file colours for now 👍

**Comment by vctls** [comment]
Wow, you sure are quick! 😄
It's nothing critical. I can use one of the working colors for now.

**Comment by sgoudham** [comment]
Haha! Sorry I missed this in my testing. I tested file colours and then disabled them but forgot to test Latte at the time.

Hope you are enjoying the other colours more 😅
