### ISSUE TITLE
Barely distinguishable selection

### ISSUE THREAD

**Issue by mamachanko** [catppuccin/jetbrains#25]
As of `2.0.2` selected text is barely distinguishable from non-selected text.

![barely-visible-highlighting](https://user-images.githubusercontent.com/1182927/199174480-6ad75892-45a9-41f4-bde7-d9f11baa9f17.png)
_(`"Hello, there!"` is selected)_

**Comment by sgoudham** [comment]
Hiya, thanks for raising this! 

I think I got too caught up in testing the highlights for multi-line selections/comments that I didn't thoroughly test the selection in the cursor line itself. I will make this more distinguishable when I have some free time!

In the meantime, if you want a quick workaround. You could head into `File > Settings > Editor > Color Scheme > General > Selection background` and adjust the background hex value yourself to try and make it better.
![image](https://user-images.githubusercontent.com/58985301/199178902-d4c7298a-920b-41db-8deb-a5d53f78ee08.png)

**Comment by mamachanko** [comment]
Thank @sgoudham for the swift response! 🚤 

I have downgraded to `2.0.1` in the meantime.

For reference, this is how a selections look like with `2.0.1`:

![nicely-distinguishable-selection](https://user-images.githubusercontent.com/1182927/199181578-ca1b91f8-a514-4a13-942e-826158b4f486.png)

**Comment by sgoudham** [comment]
How do you feel about this? Do you think this still needs to be bumped up more? @mamachanko 
![image](https://user-images.githubusercontent.com/58985301/199182036-95b5f0a0-1928-4e6e-b0fd-5bdbcf0dd670.png)

**Comment by mamachanko** [comment]
It's tricky to say. But, personally, I prefer the clarity displayed by `2.0.1`. So yes, I think it needs to be bumped a tad more.

However, I am speaking from personal preference and I have no idea if this is in line with the catppucin scheme/palette as a whole.

Nonetheless, appreciating you asking. 🙇🏻

**Comment by sgoudham** [comment]
It's really difficult because highlights on comments and text were worse off in previous versions. As for the Catppuccin palette, there are not enough colours defined in our palette to handle all the Jetbrains highlights, so we're just using an opacity function for the selection background. It's just a matter of what looks _good._

I've bumped it up a tad more, so these are the highlights now: I think this is pretty okay to release a new version with? 

Cursorline:
![image](https://user-images.githubusercontent.com/58985301/199184501-4d098b0e-b351-48a4-b46f-4386f88a8e56.png)

Multiline w/ Comment:
![image](https://user-images.githubusercontent.com/58985301/199184547-5baeaf0b-8f65-469f-bf4a-a3fbdc7fa124.png)


Ultimately, we want this theme to be super extensible so pending a... `kotlin rewrite`, we'd be able to give the user the option to choose different highlights (I think!) @mamachanko

**Comment by sgoudham** [comment]
Sorry I've been pretty busy the past few days, will try and get a release published by mid next week!

**Comment by mamachanko** [comment]
Don't worry at all! Please, don't stress. It's all good.

**Comment by mamachanko** [comment]
![2 0 3](https://user-images.githubusercontent.com/1182927/200159334-f7be8899-ee75-4ba0-a266-0493152a2682.png)
`2.0.3` - 👍🏻
