### ISSUE TITLE
Better support for New UI

### ISSUE THREAD

**Issue by widersky** [catppuccin/jetbrains#27]
Hello! Great theme - but I have a few comments:

1. When I use the new ui (here PHP Storm), the line separating the top "titlebar" from the rest of the application appears only above the sidebar. I think it should be over the entire width of the window in the same way as in the case of the status bar (screenshot below).

![Zrzut ekranu 2022-11-6 o 12 47 08](https://user-images.githubusercontent.com/45122321/200168713-c9bccba0-7c4e-4514-801e-93d3923a578b.png)
![Zrzut ekranu 2022-11-6 o 12 48 38](https://user-images.githubusercontent.com/45122321/200168798-82676a56-a8c5-46e1-9f19-e882a30b0a71.png)

2. I think the line separating the numbering of the line from the code looks strange, but it seems to me that there should also be a line separating the side panel from the editor.

![Zrzut ekranu 2022-11-6 o 12 50 34](https://user-images.githubusercontent.com/45122321/200168909-2792a1fe-2329-4968-b825-19cd2c7d7860.png)

**Comment by sgoudham** [comment]
Hiya, thanks for raising this. 

With regards to:
1. I'm not sure this can be controlled. I can double-check, but I don't think we can move around elements or add lines anywhere. It might be the case that the line is currently the same colour as the background, which we can fix. I'll look into this.
2. I'll be honest, _I have no idea_ why the file tree isn't `crust` as that would match the current theme on the existing UI. I would have thought the same highlight tokens would have carried over, but I haven't checked. It could also be because the new UI is still technically in preview, and it could magically fix itself (if they don't introduce a new highlight token for it) 

     (What it really should look like)
     ![image](https://user-images.githubusercontent.com/58985301/200675888-58f29fb5-c430-4ec1-93c5-31384875d7b6.png)

**Comment by sgoudham** [comment]
Had a deeper look into this, and found something interesting! @widersky 

When inspecting the highlights using their internal `Look and Feel` tool, you can see that the `Tree.background` is actually set to a different colour than `base` but... JetBrains is clearly just ignoring that field. Changing the colour through the UI also didn't affect the tree background :/
![image](https://user-images.githubusercontent.com/58985301/201482233-33c1fc7c-bf11-451c-b587-50545fa48746.png)

As for the lines, I couldn't see any highlights for the lines :/ so I'm afraid I won't be able to do anything there. 

Sorry, I couldn't reply with better news but I'll just be playing the waiting game until the new UI is properly released and working as intended!

**Comment by nekowinston** [comment]
I also gave this a shot, and found *some* selectors to improve the new UI. You can follow the progress in #38.

**Comment by sgoudham** [comment]
Thanks, winston! Really appreciate you digging correctly into it and finding some new selectors. We should be able to include these changes for the next release now!
