### ISSUE TITLE
Selected text better color distinction

### ISSUE THREAD

**Issue by kkrypt0nn** [catppuccin/jetbrains#30]
Currently when you click on a line and select a portion of text on the same line it is very hard to recognize what you have selected without looking precisely at it. VSC on the other hand has much lighter color when selecting text.

| VSC | IntelliJ IDEA |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/43011723/200576842-c3729c1d-dcc7-4d47-a5e7-529c71c3b9e3.png) | ![image](https://user-images.githubusercontent.com/43011723/200576612-1a9281f3-f6b8-411c-a51a-b313d888f068.png) |

Changing it to have the same color would benefit a lot when trying to see which part is selected. VSC seems to be using
```ts
"editor.selectionBackground": palette.surface2,
"editor.selectionHighlightBackground": opacity(palette.overlay2, 0.4),
```
roughly looking at [the code](https://github.com/catppuccin/vscode/blob/f2cd03f0b5809633683f47a0390d70f5793416e9/src/theme/uiColors.ts#L195-L196).

**Comment by sgoudham** [comment]
Thanks for raising this. 

While I agree that VSCode has better highlights for this. There's a small tradeoff being made here:

1. VS selection highlights only actually select the text and don't highlight the cursor line behind it, making it easier to select a lighter colour
2. I don't believe comments are well highlighted/readable with the lighter colour. 

Having messed with the colours, I've found that it's really hard to make the selection background highlight look good for normal code and comments :/ 

I'd be super happy if someone could mess around with it enough to make it look good for both

**Comment by BButner** [comment]
> Thanks for raising this.
> 
> While I agree that VSCode has better highlights for this. There's a small tradeoff being made here:
> 
> 1. VS selection highlights only actually select the text and don't highlight the cursor line behind it, making it easier to select a lighter colour
> 2. I don't believe comments are well highlighted/readable with the lighter colour.
> 
> Having messed with the colours, I've found that it's really hard to make the selection background highlight look good for normal code and comments :/
> 
> I'd be super happy if someone could mess around with it enough to make it look good for both

Too be fair, using the VSCode theme as a reference... The highlighting there has the same issue with the comments, they almost disappear:

![image](https://user-images.githubusercontent.com/39167186/212963102-f3151149-ad37-45ca-8550-f7e431f75773.png)

I think the tradeoff would be worth it. Personally, I'd rather have a higher contrast highlight color and not be able to read comments while I'm doing so.

**Comment by pohy** [comment]
I have also discovered an additional issue inside dialogs.  
`ToggleSite.tsx` in the `To` input field is highlighted/selected.
![image](https://user-images.githubusercontent.com/2036806/213735316-4bf04e11-039a-4c7a-a687-b4c7916967a9.png)

(macOS WebStorm 2022.3.1, Catpuccin 2.0.7 Macchiato variant)

**Comment by sgoudham** [comment]
> > Thanks for raising this.
> > While I agree that VSCode has better highlights for this. There's a small tradeoff being made here:
> > 
> > 1. VS selection highlights only actually select the text and don't highlight the cursor line behind it, making it easier to select a lighter colour
> > 2. I don't believe comments are well highlighted/readable with the lighter colour.
> > 
> > Having messed with the colours, I've found that it's really hard to make the selection background highlight look good for normal code and comments :/
> > I'd be super happy if someone could mess around with it enough to make it look good for both
> 
> Too be fair, using the VSCode theme as a reference... The highlighting there has the same issue with the comments, they almost disappear:
> 
> ![image](https://user-images.githubusercontent.com/39167186/212963102-f3151149-ad37-45ca-8550-f7e431f75773.png)
> 
> I think the tradeoff would be worth it. Personally, I'd rather have a higher contrast highlight color and not be able to read comments while I'm doing so.
> 
> If you're fine with this tradeoff/if enough people thumbs up here, I'm happy to PR this to match the color that VSCode uses.

Funnily enough, the highlights were the same as VSCode in the earlier releases and then an issue (#24) was raised about comments not being visible ahaha!

**Comment by sgoudham** [comment]
> I have also discovered an additional issue inside dialogs. `ToggleSite.tsx` in the `To` input field is highlighted/selected. Honestly, I cannot distinguish the selection from the background even upon close inspection.
> 
> ![image](https://user-images.githubusercontent.com/2036806/213735316-4bf04e11-039a-4c7a-a687-b4c7916967a9.png)
> 
> (macOS WebStorm 2022.3.1, Catpuccin 2.0.7 Macchiato variant)

Hmmm, this is quite weird. I don't think there are any different highlights for these dialogs but I could be wrong. I'll try to look into it when I have time! Running pretty low on that right now 😅

**Comment by sgoudham** [comment]
Hello! Finally getting around to revisiting this. 

As per recommendations suggested on discord, I've updated the comments to be `overlay2` and increased the contrast on the selection highlight. 

What do people think about this for the next release? (Excluded Frappe, Macchiato since they're basically the same as Mocha in the screenshots below)

@kkrypt0nn @BButner @pohy 

`Mocha`
![image](https://user-images.githubusercontent.com/58985301/229230236-9e130a30-b9c2-49d0-ab68-ca87fe04d39a.png)
![image](https://user-images.githubusercontent.com/58985301/229230499-23082906-a083-4dfc-87cb-c716c487de56.png)

`Latte`
![image](https://user-images.githubusercontent.com/58985301/229229908-56162b3f-7300-4ff5-9d9f-00f1099c3b26.png)
![image](https://user-images.githubusercontent.com/58985301/229230086-9a610841-e74f-4474-abd2-b8e6eeca0677.png)

**Comment by kkrypt0nn** [comment]
Looking amazing to me :D

**Comment by sgoudham** [comment]
Great! I'll close this as the new changes are implemented with the release of `2.1.0`
I'd imagine it'll be reviewed and released to the marketplace from W.B Monday 3rd April!

**Comment by sgoudham** [comment]
Re-opening this as I incorrectly read the suggestion to be `overlay2` instead of `overlay0`. Our NeoVim & VsCode ports use that at the minute so I would like to match them and keep the legibility on the selection highlight. 

It was pointed out to me that using `overlay2` does not make the comments stand out on their own enough, which I do agree with looking back at it.

How do people feel about the following screenshots? We are using `overlay0` for comments now and I've tried to tweak the selection highlights. @kkrypt0nn @BButner 

`Mocha`
![image](https://user-images.githubusercontent.com/58985301/229349405-02f7c1f6-7b1a-4b5a-933c-ceeeb7eb3d9f.png)
![image](https://user-images.githubusercontent.com/58985301/229349420-6edf7e79-7745-444a-ba09-3babae111c2a.png)
![image](https://user-images.githubusercontent.com/58985301/229349444-488ee78f-fe93-44f5-b4a2-a2dd54369961.png)

`Latte`
![image](https://user-images.githubusercontent.com/58985301/229349297-cec5599c-4010-4259-a827-a33338bd0b19.png)
![image](https://user-images.githubusercontent.com/58985301/229349310-745bf2db-1d91-4c56-8471-dd7e8165b0de.png)
![image](https://user-images.githubusercontent.com/58985301/229349321-ce24b2f8-9d7e-4556-b733-535314b8c6d8.png)

I like it as it's a middle ground between the old comments and the new ones proposed above. If it's fine, I'll make a 2.1.1 release "fixing" this.

**Comment by kkrypt0nn** [comment]
@sgoudham To me it looked already nice before, following the suggestion of changing the color used makes it stand out even better, looking awesome to me ✨
