### ISSUE TITLE
Hi, please fix blending of colors between different bars in new UI. I really like your theme, cheers.

### ISSUE THREAD

**Issue by naavid-morshed** [catppuccin/jetbrains#70]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/97723991/236083457-a434a260-5438-4cad-8627-edfe1ea4b58d.png">

**Comment by EzioTheDeadPoet** [comment]
#79 Is one example of those issues!

Additionally when you work with text inputs for the database integration you have to guess where those fields are, because they lack proper borders.

And the line that can be seen between the version control section and `Project \/` should extend from there all the way to the left and right borders of the app.
