### ISSUE TITLE
Port VSCode Icons

### ISSUE THREAD

**Issue by gavzla** [catppuccin/jetbrains#76]
### The Visual Studio Code icons of the catppuccin theme are awesome, can you port them to these IDE's? Thank you!

<img width="753" alt="CleanShot 2023-06-09 at 12 24 30@2x" src="https://github.com/catppuccin/jetbrains/assets/11657368/e526db64-4afb-4c1f-a63b-49800e6d74c6">

**Comment by quentinguidee** [comment]
For any development on this issue, we have chosen to do it in a separate plugin, so that we can update the icons without having to republish all the themes.

Current development lives here: https://github.com/quentinguidee/catppuccin-jetbrains-icons.

The icons injection mechanism is setup. We now need to figure out how to decouple icons from VSCode.
